#!/usr/bin/env zsh

if [[ "$(uname)" == "Darwin" ]]; then
  alias copy="pbcopy <"

  alias docker-start="docker-machine start dev"
  alias docker-stop="docker-machine stop dev"

elif [[ "$(uname)" == "Linux" ]]; then
  alias open="xdg-open >/dev/null 2>&1"
  alias copy='xclip -selection c'              # $ echo "copy to clipboard" | copy

# Package manager aliases
  alias agt="sudo apt-get"
  alias agi="sudo apt-get install"
  alias agui="sudo sh -c 'apt-get update; apt-get -y install'"
  alias agr="sudo apt-get remove"
  alias acs="apt-cache search"
  alias agu="sudo apt-get update"
  alias aguu="sudo sh -c 'apt-get update && apt-get -y upgrade'"

  alias pc="pacman"
  alias pcs="sudo pacman -S"
  alias pcsy="sudo pacman -Syyu"
  alias pcss="pacman -Ss"
fi

# General command line aliases
alias sl="ls"
alias sl="l"
alias ls="gls --color=auto --group-directories-first -lA"
alias ivm="vim"
alias v="vim"
alias t="tree ."
alias subl="subl >/dev/null 2>&1"                            # Open sublime text
alias c="clear"
alias s="sudo"
alias ss="sudo su"
alias viminstall="vim +PluginInstall +qall"         # Install Vim vundle plugins

alias hack.exe="export GREP_COLOR='1;32'; cat /dev/urandom | hexdump -C | grep --color=auto \"ca fe\""
alias myip="curl ifconfig.me"

# Docker Aliases
alias dps="docker ps"
alias di="docker images"
alias ds="docker save"
alias drm="docker rm"
alias dk="docker kill"
alias dr="docker run"

alias npmi="npm install"
alias npmi="npm install --save-dev"
alias npmis="npm install --save"
alias npmg="sudo npm install -g"

alias netscan="sudo arp-scan --interface=en0 --localnet"

alias bnode="babel-node --presets es2015"

# Kube Config Setters
#alias kubeprodmain='export KUBECONFIG=~/.kube/stockx.prod.main'
alias kubeprod='export AWS_SDK_LOAD_CONFIG=1; export KUBECONFIG=~/.kube/kubeconfig-stark-production; export AWS_PROFILE=production'
alias kubestaging='export AWS_SDK_LOAD_CONFIG=1; export KUBECONFIG=~/.kube/kubeconfig-arryn-staging-redux; export AWS_PROFILE=arryn-staging-redux'
alias kubesandbox='export AWS_SDK_LOAD_CONFIG=1; export KUBECONFIG=~/.kube/kubeconfig-dev-sandbox-redux; export AWS_PROFILE=dev-sandbox-redux'

# AWS Cli creds
alias awsprod='export AWS_PROFILE=production'
alias awsstaging='export AWS_PROFILE=staging'
alias awssandbox='export AWS_PROFILE=sandbox'

alias helm2="/usr/local/opt/helm@2/bin/helm"
alias helm3="/usr/local/opt/helm@3/bin/helm"

alias bp="source ~/.zshrc"

